displayName=Soulflame Horn Buff Tracker
author=Specz, NuclearDrone
description=Shows a message and overlay for the Soulflame Horn special attack.
tags=combat, buff, horn
plugins=soulflamehorn.SoulflameHornPlugin